server:
  port: 8080
  servlet:
    context-path: /order-service

logging:
  level:
    root: INFO

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:./h2db
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  flyway:
    clean-disabled: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
  metrics:
    tags:
      application: ${HOSTNAME}

